### ISSUE TITLE
GItHub repo name is different to R package name

### ISSUE THREAD

**Issue by trianglegirl** [jr-packages/jrRstan#2]
Package is name is "jrRstan"
GitHub repo name is "jrStan"

Can I rename GitHub repo to standardise?

**Comment by csgillespie** [comment]
Yes. But wait until Friday to be sure (we're running a Stan course this week)

**Comment by trianglegirl** [comment]
Yep - I've just set up the VM for it. Will change post-course. Cheers

**Comment by trianglegirl** [comment]
I've changed this now, and travis has also updated. 
I edited the "build passing" badge links in our drat repo. Think that should be everything.
